
CREATE TABLE public.student
(
    age integer DEFAULT 20 CHECK(age >= 16),
    faculty_id bigint,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(255) NOT NULL UNIQUE, //ненулевое, уникальное
    CONSTRAINT student_pkey PRIMARY KEY (id),
    CONSTRAINT fk6geq7tnjed7u4hvgv1ac6lyh FOREIGN KEY (faculty_id)
        REFERENCES public.faculty (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

CREATE TABLE public.faculty
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    color character varying(255) COLLATE pg_catalog."default",
    name character varying(255) COLLATE pg_catalog."default",
	UNIQUE (color, name),//ограничение уникальности пары цвет/название
    CONSTRAINT faculty_pkey PRIMARY KEY (id)

)